'<auto-generated />

Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports Reqnroll
Imports Reqnroll.BoDi
Imports Reqnroll.MSTest.ReqnrollPlugin
Imports System
Imports System.Reflection
Imports System.CodeDom.Compiler
Imports System.Runtime.CompilerServices

<GeneratedCode("Reqnroll", "REQNROLL_VERSION")>
<TestClass>
Public NotInheritable Class PROJECT_ROOT_NAMESPACE_MSTestAssemblyHooks
    Public Class MsTestRuntimeAdapter
        Implements IMsTestRuntimeAdapter

        Private ReadOnly _globalTestContext As TestContext

        Public Sub New(globalTestContext As TestContext)
            _globalTestContext = globalTestContext
        End Sub

        Public Sub RegisterGlobalTestContext(container As IObjectContainer) Implements IMsTestRuntimeAdapter.RegisterGlobalTestContext
            container.RegisterInstanceAs(_globalTestContext)
        End Sub

        Public Function ResolveTestContext(container As IObjectContainer) As Object Implements IMsTestRuntimeAdapter.ResolveTestContext
            Return container.Resolve(Of TestContext)()
        End Function

        Public Sub TestContextWriteLine(testContext As Object, message As String) Implements IMsTestRuntimeAdapter.TestContextWriteLine
            DirectCast(testContext, TestContext).WriteLine(message)
        End Sub

        Public Sub TestContextAddResultFile(testContext As Object, filePath As String) Implements IMsTestRuntimeAdapter.TestContextAddResultFile
            DirectCast(testContext, TestContext).AddResultFile(filePath)
        End Sub

        Public Sub ThrowAssertInconclusiveException(message As String) Implements IMsTestRuntimeAdapter.ThrowAssertInconclusiveException
            Assert.Inconclusive(message)
        End Sub

        Public Function IsInconclusiveException(exception As Exception) As Boolean Implements IMsTestRuntimeAdapter.IsInconclusiveException
            Return TypeOf exception Is AssertInconclusiveException
        End Function
    End Class

    <AssemblyInitialize>
    <MethodImpl(MethodImplOptions.NoInlining)>
    Public Shared Async Function AssemblyInitializeAsync(testContext As TestContext) As Task
        Dim currentAssembly As Assembly = GetType(PROJECT_ROOT_NAMESPACE_MSTestAssemblyHooks).Assembly
        Dim containerBuilder As New MsTestContainerBuilder(New MsTestRuntimeAdapter(testContext))
        Await Global.Reqnroll.TestRunnerManager.OnTestRunStartAsync(currentAssembly, containerBuilder)
    End Function

    <AssemblyCleanup>
    <MethodImpl(MethodImplOptions.NoInlining)>
    Public Shared Async Function AssemblyCleanupAsync() As Task
        Dim currentAssembly As Assembly = GetType(PROJECT_ROOT_NAMESPACE_MSTestAssemblyHooks).Assembly
        Await Global.Reqnroll.TestRunnerManager.OnTestRunEndAsync(currentAssembly)
    End Function

End Class
