using Microsoft.VisualStudio.TestTools.UnitTesting;
using Reqnroll.TestProjectGenerator;

namespace Reqnroll.SystemTests.Generation;

/// <summary>
/// The purpose of these tests to verify that the tests generated by the
/// MsTest generator compile and can execute with MsTest.
/// </summary>
[TestClass]
[TestCategory("MsTest4")]
public class MsTest4GenerationTest : GenerationTestBase
{
    protected override void TestInitialize()
    {
        base.TestInitialize();
        _testRunConfiguration.UnitTestProvider = UnitTestProvider.MSTest4;
    }

    /// <summary>
    /// MsTest v2.* defines the [DataRow] attribute with a ctor that cannot handle if the second
    /// parameter of the attribute is a string[]. This causes problems with single-column examples,
    /// because in this case the second parameter is a list of example block tags passed in as string[].
    /// </summary>
    [TestMethod]
    public void Generator_handles_tagged_examples_block_with_single_column()
    {
        AddScenario(
            """
            Scenario Outline: Sample Scenario Outline
                When <what> happens
            @example_tag
            Examples:
                | what |
                | foo  |
                | bar  |
            Examples: Second example without tags - in this case the tag list is null.
                | what |
                | baz  |
            """);
        _projectsDriver.AddPassingStepBinding();

        ExecuteTests();

        ShouldAllScenariosPass(3);
    }
}