using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Reqnroll.TestProjectGenerator;

namespace Reqnroll.SystemTests.Generation;

/// <summary>
/// The purpose of these tests to verify that the tests generated by the
/// xUnit generator compile and can execute with xUnit.
/// </summary>
[TestClass]
[TestCategory("TUnit")]
public class TUnitTestGenerationTest : GenerationTestBase
{
    protected override void TestInitialize()
    {
        base.TestInitialize();
        _testRunConfiguration.UnitTestProvider = UnitTestProvider.TUnit;
    }

    protected override string GetExpectedPendingOutcome() => "Failed";
    protected override string GetExpectedUndefinedOutcome() => "Failed";

    protected override void AssertIgnoredScenarioOutlineExampleHandled()
    {
        Assert.Inconclusive("Issue with current TUnit Version (https://github.com/thomhurst/TUnit/issues/2904). Check again and remove inconclusive if a fix is available.");
        //_vsTestExecutionDriver.LastTestExecutionResult.LeafTestResults
        //                      .Should().ContainSingle(tr => tr.TestName.StartsWith("SO") && tr.TestName.Contains("ignored"))
        //                      .Which.Outcome.Should().Be(GetExpectedIgnoredOutcome());
    }
}
