using Microsoft.VisualStudio.TestTools.UnitTesting;
using Reqnroll.TestProjectGenerator;

namespace Reqnroll.SystemTests.Generation;

/// <summary>
/// The purpose of these tests to verify that the tests generated by the
/// xUnit generator compile and can execute with xUnit.
/// </summary>
[TestClass]
[TestCategory("xUnit")]
public class XUnitGenerationTest : GenerationTestBase
{
    protected override void TestInitialize()
    {
        base.TestInitialize();
        _testRunConfiguration.UnitTestProvider = UnitTestProvider.xUnit;
    }

    protected override string GetExpectedPendingOutcome() => "Failed";
    protected override string GetExpectedUndefinedOutcome() => "Failed";

    protected override void AssertScenarioLevelParallelExecution()
    {
        //nop - xUnit currently does not support method-level parallelization
    }

    [TestMethod]
    public void AfterTestRun_hook_can_execute_longer_async_actions()
    {
        AddSimpleScenario();
        AddPassingStepBinding();
        AddHookBinding("AfterTestRun", 
                       code: "await Task.Delay(TimeSpan.FromMilliseconds(100));",
                       asyncHook: true);

        ExecuteTests();

        _bindingDriver.AssertExecutedHooksEqual("AfterTestRun");
        ShouldAllScenariosPass();
    }

}