using Microsoft.VisualStudio.TestTools.UnitTesting;
using Reqnroll.TestProjectGenerator.Driver;
using Reqnroll.TestProjectGenerator;

namespace Reqnroll.SystemTests.ExternalPlugins;

[TestClass]
public class SpecSyncPluginTest : ExternalPluginsTestBase
{
    protected override void TestInitialize()
    {
        base.TestInitialize();
        _testRunConfiguration.UnitTestProvider = UnitTestProvider.MSTest;
        _projectsDriver.AddNuGetPackage("SpecSync.AzureDevOps.TestSuiteBasedExecution.Reqnroll", "3.4.23");
    }

    [TestMethod]
    public void SpecSync_should_work_with_Reqnroll()
    {
        AddFeatureFileFromResource("SpecSyncPlugin/SpecSyncTestFeature.feature", resourceGroup: "ExternalPlugins");
        AddContentFileFromResource("SpecSyncPlugin/specsync.json", resourceGroup: "ExternalPlugins");
        AddPassingStepBinding();

        ExecuteTests();

        ShouldAllScenariosPass(_preparedTests + 1); // one extra test generated by the plugin
    }

    [TestMethod]
    [TestCategory("MsBuild")]
    public void SpecSync_should_work_with_Reqnroll_on_DotNetFramework_generation()
    {
        // compiling with MsBuild forces the generation to run with .NET Framework
        _compilationDriver.SetBuildTool(BuildTool.MSBuild);
        SpecSync_should_work_with_Reqnroll();
    }

}