using FluentAssertions;
using Reqnroll.TestProjectGenerator;
using Xunit;
using Xunit.Abstractions;

namespace Reqnroll.SystemTests;

/// <summary>
/// The purpose of these tests to verify that the tests generated by the MsTest
/// generator compile and can execute with MsTest.
/// </summary>
public class MsTestGeneratorTest : SystemTestBase
{
    public MsTestGeneratorTest(ITestOutputHelper testOutputHelper) : base(testOutputHelper)
    {
        _testRunConfiguration.UnitTestProvider = UnitTestProvider.MSTest;
    }

    [Fact]
    public void GeneratorAllIn_sample_can_be_handled()
    {
        PrepareGeneratorAllInSamples();

        ExecuteTests();

        ShouldAllScenariosPass();
    }

    // This is an example of a test that verifies a special case


    /// <summary>
    /// MsTest v2.* defines the [DataRow] attribute with a ctor that cannot handle if the second
    /// parameter of the attribute is a string[]. This causes problems with single-column examples,
    /// because in this case the second parameter is a list of example block tags passed in as string[].
    /// </summary>
    [Fact]
    public void Generator_handles_tagged_examples_block_with_single_column()
    {
        AddScenario(
            """
            Scenario Outline: Sample Scenario Outline
                When <what> happens
            @example_tag
            Examples:
                | what |
                | foo  |
                | bar  |
            Examples: Second example without tags - in this case the tag list is null.
                | what |
                | baz  |
            """);
        _projectsDriver.AddPassingStepBinding();

        ExecuteTests();

        ShouldAllScenariosPass(3);
    }
}