namespace Reqnroll.StepBindingSourceGenerator;

internal class StepDefinitionEmitter
{
    public string EmitStepDefinitionClass(StepDefinitionClassInfo stepDefinitionClass)
    {
        var builder = new CSharpBuilder();

        builder.AppendLine("// <auto-generated />");

        builder.Append("namespace ").AppendLine(stepDefinitionClass.ClassNamespace);
        builder.AppendBodyBlock(builder =>
        {
            builder
                .Append("internal static partial class ")
                .Append(stepDefinitionClass.ClassName)
                .AppendLine("Catalog");

            builder.AppendBodyBlock(builder => 
            {
                builder
                    .Append("public static Reqnroll.Bindings.StepDefinitionDescriptor ")
                    .Append(stepDefinitionClass.Name)
                    .AppendLine("Definition { get; } = new Reqnroll.Bindings.StepDefinitionDescriptor(")
                    .BeginBlock();

                builder
                    .Append('"')
                    .Append(stepDefinitionClass.Keyword.ToString())
                    .Append(' ')
                    .Append(stepDefinitionClass.TextPattern)
                    .AppendLine("\",");

                builder.Append("StepDefinitionType.").Append(stepDefinitionClass.Keyword.ToString()).AppendLine(',');

                builder.EndBlock();
            });
        });

        return builder.ToString();
    }
}
